"""Add reviews to db

Revision ID: 19de4bdc3a2d
Revises: 5e7ca5f0b2cc
Create Date: 2025-12-27 21:34:37.757566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '19de4bdc3a2d'
down_revision: Union[str, Sequence[str], None] = '5e7ca5f0b2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
